spring:
  datasource:
    url: jdbc:mysql://localhost:3306/everyday?characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name=com: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: cn.yellowgg.everyday.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
